### ISSUE TITLE
Error "AttributeError: _2D"

### ISSUE THREAD

**Issue by yerang823** [hxngiee/DiffFace#11]
> Traceback (most recent call last):
>   File "/data/docker/yerang/DiffFace/main.py", line 6, in <module>
>     image_editor = ImageEditor(args)
>   File "/data/docker/yerang/DiffFace/optimization/image_editor.py", line 123, in __init__
>     self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
>   File "/opt/conda/lib/python3.9/enum.py", line 429, in __getattr__
>     raise AttributeError(name) from None
> AttributeError: _2D

Solution:
Replace image_editor.py file
"_2D" -> "TWO_D"

It works!!!!!! 👍👍🔥

**Comment by shuishiwojiade** [comment]
有效

**Comment by HowCCB** [comment]
> > Traceback (most recent call last):
> > File "/data/docker/yerang/DiffFace/main.py", line 6, in 
> > image_editor = ImageEditor(args)
> > File "/data/docker/yerang/DiffFace/optimization/image_editor.py", line 123, in **init**
> > self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
> > File "/opt/conda/lib/python3.9/enum.py", line 429, in **getattr**
> > raise AttributeError(name) from None
> > AttributeError: _2D
> 
> Solution: Replace image_editor.py file "_2D" -> "TWO_D"
> 
> It works!!!!!! 👍👍🔥

Work!! THX

**Comment by harry2141985** [comment]
can you explain how exactly you fixed this error
