### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'with_stem'

### ISSUE THREAD

**Issue by qym77** [hxngiee/DiffFace#23]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    image_editor.edit_image_by_prompt()
  File "/root/DiffFace/optimization/image_editor.py", line 393, in edit_image_by_prompt
    visualization_path = visualization_path.with_stem(f"{visualization_path.stem}_i_{iteration_number}_b_{0}")
AttributeError: 'PosixPath' object has no attribute 'with_stem'

**Comment by seinfinity** [comment]
> Traceback (most recent call last): File "main.py", line 7, in image_editor.edit_image_by_prompt() File "/root/DiffFace/optimization/image_editor.py", line 393, in edit_image_by_prompt visualization_path = visualization_path.with_stem(f"{visualization_path.stem}_i_{iteration_number}_b_{0}") AttributeError: 'PosixPath' object has no attribute 'with_stem'

I changed **with_stem** to **with_name** on line 393 in the image_editor.py file, and it worked!
